model: "allenai/OLMo-1B-Instruct-hf"
dataset: "/path/to/data"
relation: P26
batch_size: 10000

count_high: 100000
count_low: 1000

template_type: question  # question or statement

template_forward: "{subject} {predicate} {object}."
relation_forward: "is married to"
template_backward: "{object} {predicate} {subject}."
relation_backward: "is married to"
